volumes:
  cache: # cache for composer, psalm, etc

services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${IMAGE_REPO}/${IMAGE_NAME}:${IMAGE_TAG}
    init: true
    container_name: ${IMAGE_NAME}
    working_dir: /app
    environment:
      APP_ENV: dev
    volumes:
      - "./:/app"
      - "cache:/cache"
    command: ["php", "bin/console"]
