services:
    App\Tests\Fake\Component\OperationService\OperationsServiceComponentFake:
        autowire: true

    App\Component\OperationsService\OperationsServiceComponentInterface: '@App\Tests\Fake\Component\OperationService\OperationsServiceComponentFake'
