services:
    App\Tests\Fake\OperationsServiceComponentFake:
        autowire: true
    App\Component\OperationsService\OperationsServiceComponentInterface: '@App\Tests\Fake\OperationsServiceComponentFake'
