# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.t-invest.token: '%env(APP_T_INVEST_TOKEN)%'
    app.t-invest.base_url: '%env(APP_T_INVEST_BASE_URL)%'
    app.t-invest.account_id: '%env(APP_T_INVEST_ACCOUNT_ID)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Component\OperationsService\OperationsServiceComponent:
        arguments:
            $token: '%app.t-invest.token%'
            $baseUrl: '%app.t-invest.base_url%'

    App\Component\UsersService\UsersServiceComponent:
        arguments:
            $token: '%app.t-invest.token%'
            $baseUrl: '%app.t-invest.base_url%'

    App\Component\InstrumentsService\InstrumentsServiceComponent:
        arguments:
            $token: '%app.t-invest.token%'
            $baseUrl: '%app.t-invest.base_url%'

    App\Tool\GetPortfolio\GetPortfolioTool:
        arguments:
            $accountId: '%app.t-invest.account_id%'

    App\Tool\GetAssetFundamentals\GetAssetFundamentalsTool: ~

    App\Factory\ToolFactory:
        arguments:
            $tools:
                get_portfolio: '@App\Tool\GetPortfolio\GetPortfolioTool'
                get_accounts: '@App\Tool\GetAccounts\GetAccountsTool'
                get_asset_fundamentals: '@App\Tool\GetAssetFundamentals\GetAssetFundamentalsTool'

    App\Command\TestClientCommand:
        arguments:
            $token: '%app.t-invest.token%'
            $baseUrl: '%app.t-invest.base_url%'
            $accountId: '%app.t-invest.account_id%'
