name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer
      - name: Cache Composer packages
        uses: actions/cache@v4
        with:
          path: |
            vendor
            ~/.cache/composer
          key: ${{ runner.os }}-php-${{ hashFiles('composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run linter
        run: ./vendor/bin/parallel-lint src tests

      - name: Run Psalm
        run: ./vendor/bin/psalm --no-progress --output-format=console

      - name: Run PHP_CodeSniffer
        run: ./vendor/bin/phpcs -q .

      - name: Run tests
        run: ./bin/phpunit
